---
- name: Download Kafka
  get_url:
    url: "https://downloads.apache.org/kafka/3.5.1/kafka_2.13-3.5.1.tgz"
    dest: /tmp/kafka.tgz
- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
- name: Configure Kafka
  template:
    src: server.properties.j2
    dest: /opt/kafka_2.13-3.5.1/config/server.properties
- name: Start Kafka
  shell: "/opt/kafka_2.13-3.5.1/bin/kafka-server-start.sh -daemon /opt/kafka_2.13-3.5.1/config/server.properties"
  become: yes